spring:
  datasource:
    username: postgres
    password: P@55w0rd
    url: 'jdbc:postgresql://localhost:5432/certificates?useSSL'
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
  profiles:
    active: dev
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
