CREATE TABLE IF NOT EXISTS tag
(
    id   INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tag_id UNIQUE (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS gift_certificate
(
    id               INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(255) NOT NULL,
    description      TEXT         NOT NULL,
    price            DECIMAL      NOT NULL,
    create_date      TIMESTAMP    NOT NULL,
    last_update_date TIMESTAMP    NOT NULL,
    duration         INT          NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_gs_id UNIQUE (id),
    CONSTRAINT uk_gs_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS gift_certificate_tag
(
    gift_certificate_id INTEGER NOT NULL
        CONSTRAINT fk_gct_gc
            REFERENCES gift_certificate,
    tag_id              INTEGER NOT NULL
        CONSTRAINT fk_gct_t
            REFERENCES tag
);
